apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx   # Matches the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80    # Port on the Service (what you'll use to access the Service)
      targetPort: 80  # Port on the Pod (NGINX container port)
  type: LoadBalancer  # Exposes the Service externally using a cloud provider's load balancer
